apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-zk01
  namespace: qiyu
  labels:
    app: zk
  annotations:
    volume.beta.kubernetes.io/storage-class: "anything"
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/zookeeper/data/zk01
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-zk02
  namespace: qiyu
  labels:
    app: zk
  annotations:
    volume.beta.kubernetes.io/storage-class: "anything"
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/zookeeper/data/zk02
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv-zk03
  namespace: qiyu
  labels:
    app: zk
  annotations:
    volume.beta.kubernetes.io/storage-class: "anything"
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/zookeeper/data/zk03
  persistentVolumeReclaimPolicy: Recycle
---