apiVersion: v1
kind: Service
metadata:
  name: eureka-nodeport
  namespace: qiyu
  labels:
    app: eureka-nodeport
spec:
  type: NodePort
  ports:
  - name: server
    port: 8761
    targetPort: 8761
    nodePort: 31761
  selector:
    app: eureka


