apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: qiyu
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - name: server
      port: 8761
      targetPort: 8761
    - name: management
      port: 8762
  selector:
    app: eureka
