apiVersion: v1
kind: Service
metadata:
  labels:
    elastic-app: kibana
  name: kibana-service
  namespace: qiyu
spec:
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30313
  selector:
    elastic-app: kibana
  type: NodePort
