apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rmqbroker2
  namespace: qiyu
  labels:
    app: rmqbroker2

spec:
  serviceName: rmqbroker2
  replicas: 1
  selector:
    matchLabels:
      app: rmqbroker2
  template:
    metadata:
      labels:
        app: rmqbroker2
    spec:
      containers:
        - name: rmqbroker
          image: foxiswho/rocketmq:4.8.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 1000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPT_EXT
              value:  -Duser.home=/opt -Xms256M -Xmx512M -Xmn256m
          command: ["sh","mqbroker","-c","/etc/rocketmq/broker2.conf","-n","rocketmq:9876","autoCreateTopicEnable=false"]
          ports:
            - containerPort: 31909
            - containerPort: 31911
            - containerPort: 31912
          volumeMounts:
            - name: vol-logs
              mountPath: /opt/logs
            - name: vol-store
              mountPath: /opt/store
            - name: vol-broker
              mountPath: /etc/rocketmq/broker2.conf
      volumes:
        - name: vol-logs
          hostPath:
            path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/rocketmq/logs-b2/
            type: Directory
        - name: vol-store
          hostPath:
              path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/rocketmq/store-b2
              type: Directory
        - name: vol-broker
          hostPath:
            path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/rocketmq/conf/broker2.conf
            type: File
