apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  namespace: qiyu
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-pod
  template:
    metadata:
      labels: 
        name: mongodb-pod
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data-store
              mountPath: "/data/db"
      volumes:
        - name: data-store
          hostPath:
              path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/mongodb/data
              type: Directory
