apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: qiyu
  labels: 
    name: mongodb-svc
spec:
  type: NodePort
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    name: mongodb
    nodePort: 32701
  selector:
    name: mongodb-pod

