apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pvc-es01
  namespace: qiyu
  labels:
    app: elasticsearch
  annotations:
    volume.beta.kubernetes.io/storage-class: "anything"
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/elasticsearch/data1
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pvc-es02
  namespace: qiyu
  labels:
    app: elasticsearch
  annotations:
    volume.beta.kubernetes.io/storage-class: "anything"
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /Volumes/HGST-MAC/gitWorkspace/kubernetes-scripts/elasticsearch/data2
  persistentVolumeReclaimPolicy: Recycle
---