apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: qiyu
  name: hostpath
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: kubernetes.io/host-path
