apiVersion: v1
kind: Service
metadata:
  name: sentinel-svc
  namespace: qiyu
  labels:
    app: sentinel
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 32702
  type: NodePort
  selector:
    app: sentinel